# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AlertViewControllerSample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AlertViewControllerSample
  pod 'EasyPeasy'
  pod 'PayWandBasicElements', :path => '../../PayWandBasicElements/'
  pod 'TtroAlertViewController', :path => '../'

  target 'AlertViewControllerSampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AlertViewControllerSampleUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
